on: [push]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variants: [8192, 9216, 10240, 11264, 12288, 13312, 14336, 20480]
        serialize: ["serialize", "dont"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: echo ${{ matrix.variants }} > count
      - run: touch ${{ matrix.serialize }}
      - run: cargo build
